---
title: "PTT Boy-Girl"
author: "Pecu"
date: "2018年4月1日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PTT Boy-Girl 分析
```
作者SpringLin (春春)    
看板Boy-Girl    
標題[求助] 真的是我價值觀問題嗎？     
時間Mon Mar 26 03:10:20 2018    
發信站: 批踢踢實業坊(ptt.cc), 來自: 27.52.197.190    
文章網址: https://www.ptt.cc/bbs/Boy-Girl/M.1522005022.A.21D.html 
```
```
作者Nianyi (かっばちゃん)    
看板Boy-Girl    
標題[心情] 被抱有好感的男性友人說978    
時間Thu Mar 29 03:09:41 2018    
發信站: 批踢踢實業坊(ptt.cc), 來自: 118.167.38.54    
文章網址: https://www.ptt.cc/bbs/Boy-Girl/M.1522264183.A.BA2.html    
```
```
作者skyline5557 (廢青)    
看板Boy-Girl    
標題[心情] 再給我們兩年的時間    
時間Thu Mar 29 00:06:24 2018
發信站: 批踢踢實業坊(ptt.cc), 來自: 101.12.165.71    
文章網址: https://www.ptt.cc/bbs/Boy-Girl/M.1522253186.A.1BD.html    
```

1. 載入所需的套件包
```{r}
library(bitops)
library(httr)
library(RCurl)
library(XML)
library(tm)
library(NLP)
library(tmcn)
library(jiebaRD)
library(jiebaR)
```

2. PTT 網路爬蟲抓出所有文章內文所對應的網址
```{r Boy-Girl Crawler1, eval=FALSE}
from <- 3860 # 2018-03-25
to   <- 3874 # 2018-03-31
prefix = "https://www.ptt.cc/bbs/Boy-Girl/index"

data <- list()
for( id in c(from:to) )
{
  url  <- paste0( prefix, as.character(id), ".html" )
  html <- htmlParse( GET(url) )
  url.list <- xpathSApply( html, "//div[@class='title']/a[@href]", xmlAttrs )
  data <- rbind( data, as.matrix(paste('https://www.ptt.cc', url.list, sep='')) )
}
data <- unlist(data)

head(data)
```

3. 利用所有文章的網址去抓所有文章內文, 並解析出文章的內容並依照 hour 合併儲存。
```{r Boy-Girl Crawler2, eval=FALSE}
library(dplyr)
getdoc <- function(url)
{
    html <- htmlParse( getURL(url) )
    doc  <- xpathSApply( html, "//div[@id='main-content']", xmlValue )
    time <- xpathSApply( html, "//*[@id='main-content']/div[4]/span[2]", xmlValue )
    temp <- gsub( "  ", " 0", unlist(time) )
    part <- strsplit( temp, split=" ", fixed=T )
    #date <- paste(part[[1]][2], part[[1]][3], part[[1]][5], sep="-")
    #date <- paste(part[[1]][2], part[[1]][5], sep="_")
    #date <- paste(part[[1]][1], part[[1]][2], sep="_")
    timestamp <- part[[1]][4]
    timestamp <- strsplit( timestamp, split=":", fixed=T )
    hour <- timestamp[[1]][1]
    #print(hour)
    name <- paste0('./DATA/', hour, ".txt")
    write(doc, name, append = TRUE)
}

sapply(data, getdoc)
```


4. 建立文本資料結構與基本文字清洗
```{r　corpus}
d.corpus <- Corpus( DirSource("./DATA") )
d.corpus <- tm_map(d.corpus, removePunctuation)
d.corpus <- tm_map(d.corpus, removeNumbers)
d.corpus <- tm_map(d.corpus, function(word) {
    gsub("[A-Za-z0-9]", "", word)
})
```

5. 進行斷詞，並依照日期建立文本矩陣 TermDocumentMatrix
```{r TDM}
mixseg = worker()
jieba_tokenizer = function(d)
{
  unlist( segment(d[[1]], mixseg) )
}
seg = lapply(d.corpus, jieba_tokenizer)

count_token = function(d)
{
  as.data.frame(table(d))
}
tokens = lapply(seg, count_token)

n = length(seg)
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0
library(knitr)
kable(head(TDM))
kable(tail(TDM))
```


5. 將已建好的 TDM 轉成 TF-IDF
```{r Boy-Girl TDM2TFIDF}
tf <- apply(as.matrix(TDM[,2:(n+1)]), 2, sum)

library(Matrix)
idfCal <- function(word_doc)
{ 
  log2( n / nnzero(word_doc) ) 
}
idf <- apply(as.matrix(TDM[,2:(n+1)]), 1, idfCal)

doc.tfidf <- TDM
# for(x in 1:nrow(TDM))
# {
#   for(y in 2:ncol(TDM))
#   {
#     doc.tfidf[x,y] <- (doc.tfidf[x,y] / tf[y]) * idf[x]
#   }
# }

tempY = matrix(rep(c(as.matrix(tf)), each = length(idf)), nrow = length(idf))
tempX = matrix(rep(c(as.matrix(idf)), each = length(tf)), ncol = length(tf), byrow = TRUE)
doc.tfidf[,2:(n+1)] <- (doc.tfidf[,2:(n+1)] / tempY) * tempX

stopLine = rowSums(doc.tfidf[,2:(n+1)])
delID = which(stopLine == 0)

kable(head(doc.tfidf[delID,1]))
kable(tail(doc.tfidf[delID,1]))


TDM = TDM[-delID,]
doc.tfidf = doc.tfidf[-delID,]
```

6. TF-IDF Hours 文章取得的重要關鍵字
```{r TopTFIDF}
TopWords = data.frame()
for( id in c(1:n) )
{
  dayMax = order(doc.tfidf[,id+1], decreasing = TRUE)
  showResult = t(as.data.frame(doc.tfidf[dayMax[1:5],1]))
  TopWords = rbind(TopWords, showResult)
}
rownames(TopWords) = colnames(doc.tfidf)[2:(n+1)]
TopWords = droplevels(TopWords)
kable(TopWords)
```

7. TF-IDF Hours 文章取得的重要關鍵字 TDM merge 視覺化
```{r TFIDF_TDM}
TDM$d = as.character(TDM$d)
AllTop = as.data.frame( table(as.matrix(TopWords)) )
AllTop = AllTop[order(AllTop$Freq, decreasing = TRUE),]

kable(head(AllTop))

TopNo = 5
tempGraph = data.frame()
for( t in c(1:TopNo) )
{
  word = matrix( rep(c(as.matrix(AllTop$Var1[t])), each = n), nrow = n )
  temp = cbind( colnames(doc.tfidf)[2:(n+1)], t(TDM[which(TDM$d == AllTop$Var1[t]), 2:(n+1)]), word )
  colnames(temp) = c("hour", "freq", "words")
  tempGraph = rbind(tempGraph, temp)
  names(tempGraph) = c("hour", "freq", "words")
}

library(ggplot2)
library(varhandle)
tempGraph$freq = unfactor(tempGraph$freq)
ggplot(tempGraph, aes(hour, freq)) + 
  geom_point(aes(color = words, shape = words), size = 5) +
  geom_line(aes(group = words, linetype = words))


kable(tail(AllTop))
```

8. 發文時間與發文量
```{r}
filenames = as.array(paste0("./DATA/",colnames(doc.tfidf)[2:(n+1)],".txt"))
sizeResult = apply(filenames, 1, file.size) / 1024
showSize = data.frame(colnames(doc.tfidf)[2:(n+1)], sizeResult)
names(showSize) = c("hour", "size_KB")

ggplot(showSize, aes(x = hour, y = size_KB)) + geom_bar(stat="identity")
```

